### ISSUE TITLE
有部分弹窗样式截图里边有，但是demo里边没有呢

### ISSUE THREAD

**Issue by zzzsssbo** [ITxiaoguang/BiometricHelper#1]

**Comment by ITxiaoguang** [comment]
是的，具体得看Android手机版本，和手机支不支持，文档写得很详细哦。https://github.com/ITxiaoguang/BiometricHelper/blob/master/README.md

**Comment by zzzsssbo** [comment]
哦哦，感觉Android指纹识别现在一个最大的问题是，不能使用特定的指纹登录，也就是说别人如果拿到你的手机后增加指纹，也可以正常登录，没办法判断初始绑定的时候用的是哪个指纹。

**Comment by ITxiaoguang** [comment]
是的，手机系统处于安全，并没有提供那么多信息

**Comment by ITxiaoguang** [comment]
是的，手机系统出于安全考虑，并没有提供那么多信息。
